### ISSUE TITLE
Left Face Button or "Y" is mapped to button 2 and cant be unmapped (new analogue pocket firmware)

### ISSUE THREAD

**Issue by SoulSwordStrike** [spiritualized1997/openFPGA-SMS#6]
The recent analogue pocket firmware now supports remapping controls, but currently by default left face button is mapped to button 2 then bottom face button to button 1 and right face button also to button 2. So if you try to assign the left face button ( Y ) to button 1 (to achieve a super gameboy type layout) it does not lose its button 2 input and you get both inputs. This default mapping of the button cant be undone and unmap all buttons does not affect it either.

**Comment by SpiralBrad** [comment]
Came here to post this same thing.

This would be easily fixable with available source code, but that will never happen.  We are FUILLY reliant on Kevtris to fix this.

Take note, anyone with issues: THIS is what supporting closed source gets you.  Problems that may potentially remain unfixed forever.

**Comment by SpiralBrad** [comment]
Hopefully this isn't some kind of fluke, but this issue seems fixed (even using the current/1.2.0 version of this core from August) when using the latest Pocket firmware, 1.1-beta-6 released 11-05.

Thanks, "kevtris".

**Comment by SoulSwordStrike** [comment]
Yes this seems to be fixed after the latest pocket firmware, thanks! Also fixed on game gear core too now.
